projectType : runtime
slackChannel : data-weave-bot
enableSlackSuccessNotifications : true
enableSlackFailedTestsNotifications : true
enableAllureTestReportStage : false
enableMavenDeployStage : false
enableReleaseStage : false
mavenSettingsXmlId : "data-weave-maven-settings"
junitTestResults: "**/target/data-weave-test-reports/TEST-*.xml"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    jdkTool: TEMURIN-JDK21
  arm:
    agentLabel: ubuntu-22.04-arm